# POST TEST 4
## Sephora Website Dataset

### Nama    : Aprisa Idma Mutiara
### NIM     : 2209106001
### Kelas   : A1 22 Kecerdasan Buatan

In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer

sephora = pd.read_csv('sephora_website_dataset.csv')
sephora_manipulation = pd.read_csv('sephora_website_manipulation_dataset.csv')

## Data Sebelum Manipulasi
Berikut ini merupakan dataset sebelum dimanipulasi, tidak memiliki nilai null dan duplikat.

In [2]:
sephora

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,MarketingFlags,MarketingFlags_content,options,details,how_to_use,ingredients,online_only,exclusive,limited_edition,limited_time_offer
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Arancia di Capri Eau de Toilette: Alcohol Dena...,1,0,0,0
1,2044816,Acqua Di Parma,Cologne,Colonia,0.7 oz/ 20 mL,4.5,76,2700,66.0,66.0,...,True,online only,- 0.7 oz/ 20 mL Spray - 1.7 oz/ 50 mL Eau d...,An elegant timeless scent filled with a fresh-...,no instructions,unknown,1,0,0,0
2,1417567,Acqua Di Parma,Perfume,Arancia di Capri,5 oz/ 148 mL,4.5,26,2600,180.0,180.0,...,True,online only,- 1oz/30mL Eau de Toilette - 2.5 oz/ 74 mL E...,Fragrance Family: Fresh Scent Type: Fresh Citr...,no instructions,Alcohol Denat.- Water- Fragrance- Limonene- Li...,1,0,0,0
3,1417617,Acqua Di Parma,Perfume,Mirto di Panarea,2.5 oz/ 74 mL,4.5,23,2900,120.0,120.0,...,True,online only,- 1 oz/ 30 mL Eau de Toilette Spray - 2.5 oz/...,Panarea near Sicily is an an island suspended ...,no instructions,unknown,1,0,0,0
4,2218766,Acqua Di Parma,Fragrance,Colonia Miniature Set,5 x 0.16oz/5mL,3.5,2,943,72.0,80.0,...,True,online only,no options,The Colonia Miniature Set comes in an iconic A...,Suggested Usage:-Fragrance is intensified by t...,Colonia: Alcohol Denat.- Water- Fragrance- Lim...,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9163,2208502,SEPHORA COLLECTION,Face Masks,The Rose Gold Mask,no size,2.0,15,6200,6.0,6.0,...,True,limited edition Â· exclusive,no options,What it is: A limited-edition- nurturing and h...,Suggested Usage:-Unfold the mask.-Apply the ma...,-Rose Quartz Extract: Hydrates dry skin. Aqua...,0,1,1,0
9164,2298909,SEPHORA COLLECTION,Lip Sets,Give Me Some Sugar Colorful Gloss Balm Set,3 x 0.32 oz/ 9 g,0.0,0,266,15.0,27.0,...,True,exclusive,no options,What it is: A set of three bestselling Colorfu...,Suggested Usage:-Apply directly to lips using ...,Colorful Gloss Balm Wanderlust: Hydrogenated P...,0,1,0,0
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,16.0,...,True,exclusive,no options,What it is: A weightless complexion booster- i...,Suggested Usage:-Use this product as the last ...,Aqua (Water)- Dimethicone- Isohexadecane- Poly...,0,1,0,0
9166,50,SEPHORA COLLECTION,no category,Gift Card,no size,5.0,46,0,50.0,50.0,...,False,0,no options,What it is:- Available in denominations of $10...,no instructions,unknown,0,0,0,0
9167,304,SEPHORA COLLECTION,no category,Happy Birthday Gift Card,no size,0.0,0,0,50.0,50.0,...,False,0,no options,What it is:\n- Available in denominations of $...,no instructions,unknown,0,0,0,0

In [3]:
sephora.isna().sum()

id                        0
brand                     0
category                  0
name                      0
size                      0
rating                    0
number_of_reviews         0
love                      0
price                     0
value_price               0
URL                       0
MarketingFlags            0
MarketingFlags_content    0
options                   0
details                   0
how_to_use                0
ingredients               0
online_only               0
exclusive                 0
limited_edition           0
limited_time_offer        0
dtype: int64

In [4]:
sephora.duplicated().sum()

0

## Data Manipulasi

Menampilkan seluruh dataset sephora website

In [5]:
sephora_manipulation

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,MarketingFlags,MarketingFlags_content,options,details,how_to_use,ingredients,online_only,exclusive,limited_edition,limited_time_offer
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Arancia di Capri Eau de Toilette: Alcohol Dena...,1,0,0,0.0
1,2044816,Acqua Di Parma,Cologne,Colonia,0.7 oz/ 20 mL,4.5,76,2700,66.0,66.0,...,True,online only,- 0.7 oz/ 20 mL Spray - 1.7 oz/ 50 mL Eau d...,An elegant timeless scent filled with a fresh-...,no instructions,unknown,1,0,0,0.0
2,1417567,Acqua Di Parma,Perfume,Arancia di Capri,5 oz/ 148 mL,4.5,26,2600,180.0,NaN,...,True,online only,- 1oz/30mL Eau de Toilette - 2.5 oz/ 74 mL E...,Fragrance Family: Fresh Scent Type: Fresh Citr...,no instructions,Alcohol Denat.- Water- Fragrance- Limonene- Li...,1,0,0,0.0
3,1417617,Acqua Di Parma,Perfume,Mirto di Panarea,2.5 oz/ 74 mL,4.5,23,2900,120.0,120.0,...,True,online only,- 1 oz/ 30 mL Eau de Toilette Spray - 2.5 oz/...,Panarea near Sicily is an an island suspended ...,no instructions,unknown,1,0,0,0.0
4,2218766,Acqua Di Parma,Fragrance,Colonia Miniature Set,5 x 0.16oz/5mL,3.5,2,943,72.0,80.0,...,True,online only,no options,The Colonia Miniature Set comes in an iconic A...,Suggested Usage:-Fragrance is intensified by t...,Colonia: Alcohol Denat.- Water- Fragrance- Lim...,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,NaN,...,True,exclusive,no options,What it is: A weightless complexion booster- i...,Suggested Usage:-Use this product as the last ...,Aqua (Water)- Dimethicone- Isohexadecane- Poly...,0,1,0,0.0
9166,50,SEPHORA COLLECTION,no category,Gift Card,no size,5.0,46,0,50.0,50.0,...,False,0,no options,What it is:- Available in denominations of $10...,no instructions,unknown,0,0,0,0.0
9167,304,SEPHORA COLLECTION,no category,Happy Birthday Gift Card,no size,0.0,0,0,50.0,50.0,...,False,0,no options,What it is:\n- Available in denominations of $...,no instructions,unknown,0,0,0,0.0
9168,304,SEPHORA COLLECTION,no category,Happy Birthday Gift Card,no size,0.0,0,0,50.0,50.0,...,False,0,no options,What it is:\n- Available in denominations of $...,no instructions,unknown,0,0,0,NaN
9169,2293181,VOLUSPA,Candles & Home Scents,White Cypress Glass Jar Candle,5.5 oz/ 156 g,4.0,14,3200,18.0,18.0,...,False,0,- 5.5 oz/ 156 g,Fragrance Family: Earthy & WoodyScent Type: Cl...,Suggested Usage:-Fragrance is intensified by t...,unknown,0,0,0,0.0

## Data Cleaning

### Cleaning NULL
Pada dataset di bawah ini, terdapat 12 nilai null pada kolom "value_price" dan 1 pada kolom "limited_time_offer"

In [6]:
print('Jumlah record yang memiliki nilai null:')
sephora_manipulation.isna().sum()

Jumlah record yang memiliki nilai null:

id                         0
brand                      0
category                   0
name                       0
size                       0
rating                     0
number_of_reviews          0
love                       0
price                      0
value_price               12
URL                        0
MarketingFlags             0
MarketingFlags_content     0
options                    0
details                    0
how_to_use                 0
ingredients                0
online_only                0
exclusive                  0
limited_edition            0
limited_time_offer         1
dtype: int64

Nilai null pada kolom "value_price" dan kolom "limited_time_offer" akan digantikan oleh modus pada masing masing jumlah kolomnya.

In [7]:
modus = SimpleImputer(strategy='most_frequent')

Kemudian gunakan fungsi fit_transform untuk mengubah nilai null pada dataset sephora_manipulation di kolom "value_price" dan  "limited_time_offer" berdasarkan modus.

In [8]:
sephora_manipulation[['value_price', 'limited_time_offer']] = modus.fit_transform (sephora_manipulation[['value_price', 'limited_time_offer']])

Terlihat pada data di bawah ini sudah tidak terdapat nilai null lagi.

In [9]:
print('Jumlah null setelah menggunakan SimpleImputer:')
sephora_manipulation.isna().sum()

Jumlah null setelah menggunakan SimpleImputer:

id                        0
brand                     0
category                  0
name                      0
size                      0
rating                    0
number_of_reviews         0
love                      0
price                     0
value_price               0
URL                       0
MarketingFlags            0
MarketingFlags_content    0
options                   0
details                   0
how_to_use                0
ingredients               0
online_only               0
exclusive                 0
limited_edition           0
limited_time_offer        0
dtype: int64

### Cleaning duplicate
Pada dataset di bawah ini terdapat 2 baris yang memiliki nilai sama atau duplikat

In [10]:
print('Nilai duplikat:', sephora_manipulation.duplicated().sum())

Nilai duplikat: 2

Untuk menghapus nilai duplikat dapat menggunakan drop _duplicates.

In [11]:
sephora_manipulation.drop_duplicates(inplace=True)

Nilai duplikat sudah tidak ada lagi karena sudah saya hapus.

In [12]:
print('Nilai duplikat:', sephora_manipulation.duplicated().sum())

Nilai duplikat: 0

## Mengganti Tipe Data

Menampilkan tipe data pada masing-masing attribut

In [13]:
print('Sebelum diubah: ')
sephora_manipulation.dtypes

Sebelum diubah:

id                          int64
brand                      object
category                   object
name                       object
size                       object
rating                    float64
number_of_reviews           int64
love                        int64
price                     float64
value_price               float64
URL                        object
MarketingFlags               bool
MarketingFlags_content     object
options                    object
details                    object
how_to_use                 object
ingredients                object
online_only                 int64
exclusive                   int64
limited_edition             int64
limited_time_offer        float64
dtype: object

Disini saya mengubah tipe data kolom "value_price" yang awalnya float menjadi integer, menggunakan perintah astype().

In [14]:
sephora_manipulation['value_price'] = sephora_manipulation['value_price'].astype('int')

Kemudian datanya dicek lagi dan ternyata pada kolom "value_price" sudah berubah menjadi integer.

In [15]:
sephora_manipulation.dtypes

id                          int64
brand                      object
category                   object
name                       object
size                       object
rating                    float64
number_of_reviews           int64
love                        int64
price                     float64
value_price                 int32
URL                        object
MarketingFlags               bool
MarketingFlags_content     object
options                    object
details                    object
how_to_use                 object
ingredients                object
online_only                 int64
exclusive                   int64
limited_edition             int64
limited_time_offer        float64
dtype: object

## Data Transformation

Untuk melakukan data transformation, harus mengetahui tipe data setiap atribut terlebih dahulu. Atribut dengan tipe data numerik dapat dilakukan data transformation. 

Pada data di bawah ini, "rating", "number_of_reviews", "price", "value_price" dapat dilakukan transformasi data.

In [16]:
sephora_manipulation.dtypes

id                          int64
brand                      object
category                   object
name                       object
size                       object
rating                    float64
number_of_reviews           int64
love                        int64
price                     float64
value_price                 int32
URL                        object
MarketingFlags               bool
MarketingFlags_content     object
options                    object
details                    object
how_to_use                 object
ingredients                object
online_only                 int64
exclusive                   int64
limited_edition             int64
limited_time_offer        float64
dtype: object

"id" dan "love" berupa numerik tapi tidak bisa transformasi data, karena id memiliki data unik dan love merupakan target. 

"online_only", "exclusive", "limited_edition", "limited_time_offer" juga tidak bisa karena dari awal sudah bernilai 0 dan 1.

### Standarisasi

In [17]:
from sklearn.preprocessing import StandardScaler

Melakukan proses transform data dengan standarisasi sehingga atribut "rating", "number_of_reviews", "price", "value_price" memiliki nilai skala 0 sampai 1.

In [18]:
ss = StandardScaler()
sephora_std = sephora_manipulation.copy()
sephora_std[['rating', 'number_of_reviews', 'price', 'value_price']] = ss.fit_transform(sephora_std[['rating', 'number_of_reviews', 'price', 'value_price']])

In [19]:
print('Nilai data sebelum scaling : ')
print(sephora_manipulation[['rating', 'number_of_reviews', 'price', 'value_price']])

print('Nilai data setelah scaling : ')
print(sephora_std[['rating', 'number_of_reviews', 'price', 'value_price']])

Nilai data sebelum scaling :
      rating  number_of_reviews  price  value_price
0        4.0                  4   66.0           75
1        4.5                 76   66.0           66
2        4.5                 26  180.0           30
3        4.5                 23  120.0          120
4        3.5                  2   72.0           80
...      ...                ...    ...          ...
9163     2.0                 15    6.0            6
9164     0.0                  0   15.0           27
9165     0.0                  0   16.0           30
9166     5.0                 46   50.0           50
9167     0.0                  0   50.0           50

[9168 rows x 4 columns]
Nilai data setelah scaling :
        rating  number_of_reviews     price  value_price
0     0.009905          -0.312308  0.337912     0.471172
1     0.506108          -0.231463  0.337912     0.288935
2     0.506108          -0.287605  2.755091    -0.440013
3     0.506108          -0.290974  1.482892     1.382357
4    -0.486299          -0.314553  0.465132     0.572415
...        ...                ...       ...          ...
9163 -1.974908          -0.299956 -0.934287    -0.925978
9164 -3.959721          -0.316799 -0.743457    -0.500759
9165 -3.959721          -0.316799 -0.722254    -0.440013
9166  1.002311          -0.265148 -0.001341    -0.035042
9167 -3.959721          -0.316799 -0.001341    -0.035042

[9168 rows x 4 columns]

### Normalisasi

In [20]:
from sklearn.preprocessing import MinMaxScaler

Melakukan proses transform data pada atribut "price" dengan normalisasi sehingga nilai min menjadi 0 dan max menjadi 1.

In [21]:
mm = MinMaxScaler()
sephora_nrml = sephora_manipulation.copy()
sephora_nrml[['price']] = mm.fit_transform(sephora_nrml[['price']])

In [22]:
print('Nilai data sebelum scaling: ')
sephora_manipulation['price'].describe()

Nilai data sebelum scaling:

count    9168.000000
mean       50.063237
std        47.164989
min         2.000000
25%        24.000000
50%        35.000000
75%        59.000000
max       549.000000
Name: price, dtype: float64

In [23]:
print('Nilai data setelah scaling: ')
sephora_nrml['price'].describe()

Nilai data setelah scaling:

count    9168.000000
mean        0.087867
std         0.086225
min         0.000000
25%         0.040219
50%         0.060329
75%         0.104205
max         1.000000
Name: price, dtype: float64

Menampilkan hasil dari normalisasi

## One Hot Encoding

In [24]:
from sklearn.preprocessing import OneHotEncoder

Menampilkan isi dari "MarketingFlags_content"

In [25]:
sephora_manipulation['MarketingFlags_content'].value_counts()

0                                                   4786
exclusive                                           1692
online only                                         1528
exclusive Â· online only                              318
limited edition Â· exclusive                          297
limited edition                                      237
limited edition Â· online only                        188
limited edition Â· exclusive Â· online only            119
limited time offer                                     2
limited time offer Â· limited edition Â· exclusive       1
Name: MarketingFlags_content, dtype: int64

Mengubah kolom "MarketingFlags_content" yang awalnya berupa kategorikal menjadi boolean (true or false / 0 or 1) menggunakan OneHotEncoder.

In [26]:
ohe = OneHotEncoder(sparse_output=False)
ohe_sephora = ohe.fit_transform(sephora_manipulation[['MarketingFlags_content']])

Memberikan nama kolom baru pada atribut "MarketingFlags_content" yang telah dipecah menjadi 10.

In [27]:
MFC_ohe = pd.DataFrame(ohe_sephora,
                        columns=['0', 'exclusive', 'online only', 'exclusive Â·online only', 'limited edition Â·exclusive', 'limited edition', 'limited edition Â· online only', 'limited edition Â·exclusive Â·online only', 'limited time offer', 'limited time offer Â·limited edition Â· exclusive'])

Setelah dilakukan one hot encoding nilainya sudah menjadi boolean yaitu 0 1.

In [28]:
MFC_ohe

,0,exclusive,online only,exclusive Â·online only,limited edition Â·exclusive,limited edition,limited edition Â· online only,limited edition Â·exclusive Â·online only,limited time offer,limited time offer Â·limited edition Â· exclusive
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
9163,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9164,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9165,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9166,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9167,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Menghapus kolom "MarketingFlags_content" kemudian menggabungkan "MFC_ohe" ke dataset. Sehingga "MarketingFlags_content" digantikan dengan kolom yang telah di one hot encoding tadi yaitu "MFC_ohe".

In [29]:
sephora_manipulation.drop(columns = ['MarketingFlags_content'], inplace=True)

In [30]:
sephora_manipulation = pd.concat([sephora_manipulation, MFC_ohe], axis=1)

In [31]:
sephora_manipulation

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,0,exclusive,online only,exclusive Â·online only,limited edition Â·exclusive,limited edition,limited edition Â· online only,limited edition Â·exclusive Â·online only,limited time offer,limited time offer Â·limited edition Â· exclusive
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2044816,Acqua Di Parma,Cologne,Colonia,0.7 oz/ 20 mL,4.5,76,2700,66.0,66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1417567,Acqua Di Parma,Perfume,Arancia di Capri,5 oz/ 148 mL,4.5,26,2600,180.0,30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1417617,Acqua Di Parma,Perfume,Mirto di Panarea,2.5 oz/ 74 mL,4.5,23,2900,120.0,120,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2218766,Acqua Di Parma,Fragrance,Colonia Miniature Set,5 x 0.16oz/5mL,3.5,2,943,72.0,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9163,2208502,SEPHORA COLLECTION,Face Masks,The Rose Gold Mask,no size,2.0,15,6200,6.0,6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9164,2298909,SEPHORA COLLECTION,Lip Sets,Give Me Some Sugar Colorful Gloss Balm Set,3 x 0.32 oz/ 9 g,0.0,0,266,15.0,27,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,30,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9166,50,SEPHORA COLLECTION,no category,Gift Card,no size,5.0,46,0,50.0,50,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9167,304,SEPHORA COLLECTION,no category,Happy Birthday Gift Card,no size,0.0,0,0,50.0,50,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Data Split

Pada metode ini, kita akan membagi dataset menjadi 2 bagian yaitu training set dan testing set dengan masing-masing proporsi 70:30.

In [32]:
from sklearn.model_selection import train_test_split

Variabel x merupakan atribut selain love, 
Variabel y berisi target yaitu atribut love.

In [33]:
X = sephora_manipulation.drop(columns='love')
y = sephora_manipulation['love']

Membuat kelas train_test_split guna membagi datanya dengan testing set 0.3.

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

Menampilkan hasil dari split data

In [35]:
print('X train: ', X_train.shape)
print('X test: ', X_test.shape)
print('y train: ', y_train.shape)
print('y test: ', y_test.shape)

X train:  (6417, 29)
X test:  (2751, 29)
y train:  (6417,)
y test:  (2751,)